# Generated by Django 2.2.6 on 2020-03-29 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date time')),
                ('status', models.CharField(blank=True, max_length=35, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pid', models.CharField(max_length=40)),
                ('amount', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(10)])),
                ('currency', models.CharField(max_length=5)),
                ('saved', models.BooleanField()),
                ('canceled', models.BooleanField()),
                ('cancel_wait', models.BooleanField()),
                ('from_vk', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('short_bank_info', models.CharField(max_length=200)),
                ('next_pay', models.DateTimeField(verbose_name='Next payment date time for saved paymemts')),
                ('last_pay_status', models.CharField(max_length=35)),
                ('last_mailed_at', models.DateTimeField(auto_now_add=True, verbose_name='Last sended email date time')),
                ('note_subj', models.CharField(blank=True, max_length=80, null=True)),
                ('note_data', models.TextField(blank=True, null=True)),
                ('pay_ref', models.CharField(max_length=16)),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
