# Generated by Django 2.2.6 on 2020-03-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=35)),
                ('long_name', models.TextField(max_length=108)),
                ('is_hural', models.BooleanField(default=True)),
                ('celebration_hural', models.BooleanField(default=False)),
                ('for_best_reincarnation', models.BooleanField(default=False)),
                ('note_allowed', models.BooleanField(default=True)),
                ('note_for_one_name', models.BooleanField(default=False)),
                ('note_fix_price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_link', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('bg_color', models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Background Color')),
                ('fg_color', models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Foreground Color')),
            ],
        ),
        migrations.CreateModel(
            name='MoonDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('day_no', models.IntegerField()),
                ('moon_day_no', models.IntegerField()),
                ('baldjinima', models.BooleanField(default=False)),
                ('dashinima', models.BooleanField(default=False)),
                ('tersuud', models.BooleanField(default=False)),
                ('modon_hohimoy', models.BooleanField(default=False)),
                ('riha', models.BooleanField(default=False)),
                ('pagshag', models.BooleanField(default=False)),
                ('good_for_haircut', models.BooleanField(default=False)),
                ('good_for_travel', models.BooleanField(default=False)),
                ('significant_day', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('lamas_checked', models.BooleanField(default=False)),
                ('bg_color', models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Background Color')),
                ('fg_color', models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Foreground Color')),
                ('day_hural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day2ritual', to='saraswati.Ritual')),
                ('morning_hural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morning2ritual', to='saraswati.Ritual')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=108, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('bg_color', models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Background Color')),
                ('fg_color', models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Foreground Color')),
                ('moonday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='saraswati.MoonDay')),
                ('ritual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='saraswati.Ritual')),
            ],
        ),
    ]
