# Generated by Django 2.2.6 on 2020-03-29 19:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saraswati', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='fg_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='moonday',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='moonday',
            name='fg_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='fg_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
    ]
