# Generated by Django 2.2.6 on 2020-04-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saraswati', '0002_monthmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='moonday',
            name='day_hural_comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='moonday',
            name='morning_hural_comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
