# Generated by Django 2.2.6 on 2020-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saraswati', '0002_auto_20200329_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bg_color',
            field=models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fg_color',
            field=models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Foreground Color'),
        ),
        migrations.AlterField(
            model_name='moonday',
            name='bg_color',
            field=models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='moonday',
            name='fg_color',
            field=models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Foreground Color'),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='bg_color',
            field=models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='fg_color',
            field=models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Foreground Color'),
        ),
    ]
